[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  timeout = 26
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
